Create a thread per event. Deleting doesn't delete thread.
colinobriendev/RaidBot pull request #51
Opened 2023-02-12 20:51 UTC by colinobriendev

Creating this in case we are alright with adding this in for now and working on a fix for deleting the thread later.

2023-02-13 22:50 UTC, lbarry00 requested changes
Looks good, just some RestAction stuff to clean up.

2023-02-13 22:50 UTC, lbarry00 commented on src/main/java/com/bp3x/raidbot/commands/lfg/LFGCommand.java
> +                ThreadChannel thread = success.createThreadChannel(plannedEvent.getLongName() + "-" + plannedEvent.getEventId()).complete();
We shouldn't need to block the thread to create the ThreadChannel, then send a message in it. Something like [this](https://github.com/DV8FromTheWorld/JDA/wiki/7\)-Using-RestAction#example-sending-a-private-message) would work better.

2023-02-13 22:50 UTC, lbarry00 commented on src/main/java/com/bp3x/raidbot/commands/lfg/LFGReactionListener.java
> +            Message message = reactionEvent.getChannel().retrieveMessageById(reactionEvent.getMessageId()).complete();
Is there a reason why this was switched to block the thread?

2023-02-13 22:50 UTC, lbarry00 commented on src/main/java/com/bp3x/raidbot/commands/lfg/LFGReactionListener.java
> +            reactionEvent.getReaction().removeReaction(reactionEvent.getUser()).submit();
Also here, why a separate `.submit()`?

2023-02-13 22:50 UTC, lbarry00 commented on src/main/java/com/bp3x/raidbot/commands/lfg/DeleteCommand.java
> +                    thread.delete().complete();
I think this can be changed to .queue() as well. You can use the Consumer params to send the success/failure messages.

2023-02-14 03:51 UTC, lbarry00 approved these changes

2023-02-15 19:33 UTC, aedandan approved these changes
Looks good to me! Great adjustment with the lambdas/ anonymous class usage. The code is less verbose now, which is nice for Java-based projects like this.

2023-02-15 20:25 UTC, merged